% Plotting PSTH results.
% (c) Si-yang Yu @ PSI 2018

% Function input: psth,    PSTH related information,(2 fields, defined below), generated by 'psth_calc.m'     
%                            cell: the cell number of PSTH
%                            bar:  the PSTH bar information, defined as an array of struct (2 fields, defined below)
%                                    bin: the number of PSTH bar
%                                    h:   the hight of PSTH bar
%                 cell_nr, the cell number for plotting
%                 type,    the type of PSTH figure, allowed value are 'hist'(histogram ONLY), 'line'(curve ONLY), and 'both'

function psth_plot(psth,cell_nr,type)
    fig_name = strcat('PSTH of Cell No.',num2str(cell_nr,'%03d'));
    figure('Name',fig_name,'NumberTitle','off')
    if strcmp(type,'hist') || strcmp(type,'both')
        hold on
        h = histogram([psth(cell_nr).bar.bin]);
            h.BinEdges = (min([psth(cell_nr).bar.bin])):(max([psth(cell_nr).bar.bin]) + 1);
            h.NumBins = size([psth(cell_nr).bar.bin],2);
            h.BinCounts = [psth(cell_nr).bar.h];
            h.EdgeColor = [0 0 0];
            h.EdgeAlpha = 0.50;
            h.FaceColor = [0 0.4470 0.7410];
            h.FaceAlpha = 0.75;
    end
    if strcmp(type,'line') || strcmp(type,'both')
        b = (min([psth(cell_nr).bar.bin]):0.05:max([psth(cell_nr).bar.bin]));
        l = interp1([psth(cell_nr).bar.bin],[psth(cell_nr).bar.h],b,'spline');
        if strcmp(type,'both')
            b = b + (h.BinWidth / 2);
        end
        hold on
        plot(b,l,'Color',[0.7686 0.1176 0.2275],'LineWidth',1.5);
    end
  % Draw 0 point reference line
    yh = max([psth(cell_nr).bar.h]) * 1.01;
    hold on
    line([0 0],[0, yh],'Color',[0.2941 0.4353 0.2667],'LineStyle','--','LineWidth',2.0);
  % Set labels
    xlabel('Bin No.');
    xlim([(min([psth(cell_nr).bar.bin]) - 1) (max([psth(cell_nr).bar.bin]) + 2)]);
    ylabel('Est. Spike Freq. (Hz)');
    ylim([0 inf]);
end