% Create time window defined spike frequency from raw spike timings.
% (c) Si-yang Yu @ PSI 2018

% Function input:  cell_spk, defined as an array of struct, generated by import_jrc_csv.m
%                  t_frm,    defined as desired time window to slide, in ms
% Function output: freq_frm, defined as an array of struct (3 fields, defined below)
%                              nr:   the cell number, 0 means noise channel
%                              tfrm: the spike timings in time window, in ms
%                              freq: spike frequencies in time window, in Hz

function freq_frm = t_win_freq(cell_spk,t_frm)
  % Input variables preparation
    n_cell = max([cell_spk.nr]);
    t_frm = t_frm / 1000;
  % Manipulation loop on cells (i = 2 to escape noise channel 0)
    i = 2;
    freq_frm(n_cell) = struct('nr',[],'tfrm',[],'freq',[]);
    while i <= n_cell+1
        freq_frm(i-1).nr = i - 1;
        t = 0;
      % Manipulation loop on spikes
        while t <= max(cell_spk(i).t)
            idx = find(cell_spk(i).t >= t & cell_spk(i).t < t+t_frm);
            t = t + t_frm;
            freq_frm(i-1).tfrm(end+1) = t * 1000;
            freq_frm(i-1).freq(end+1) = size(idx,1) / t_frm;
        end
        i = i + 1;
    end
end