% Calculate Z-score with defined baseline for spike frequency analysis.
% (c) Si-yang Yu @ PSI 2018

% Function input:  freq_frm,  defined as an array of struct (3 fields, defined below), generated by 't_win_freq.m'
%                               nr:   the cell number, 0 means noise channel
%                               tfrm: the spike timings in time window, in ms
%                               freq: spike frequencies in time window, in Hz
%                  base_time, time to calculate baseline parameters, in ms
% Function output: score,     defined as an array of struct (3 fields, defined below)
%                               nr:   the cell number, 0 means noise channel
%                               t:    the spike timings in time window, in ms
%                               z:    the z score values

function score = z_score_freq(freq_frm,base_time)
    t_base = t_base * 1000;
    idx  = freq_frm(1).tfrm < base_time;
    score(size(freq_frm,2)) = struct('nr',[],'t',[],'z',[]);
    for i = 1:size(freq_frm,2)
        base_mean = mean(freq_frm(i).freq(idx));
        base_std = std(freq_frm(i).freq(idx));
        score(i).nr = i;
        score(i).t = freq_frm(i).tfrm;
        score(i).z = (freq_frm(i).freq - base_mean) / base_std;
    end
end